"""Pydantic schemas for the goal proposal system."""

from enum import StrEnum

from pydantic import BaseModel, Field


class GoalType(StrEnum):
    """Types of strategic goals the system can propose."""

    PERFORMANCE_OPTIMIZATION = "performance_optimization"
    COST_REDUCTION = "cost_reduction"
    RELIABILITY_IMPROVEMENT = "reliability_improvement"
    WORKFLOW_RESTRUCTURING = "workflow_restructuring"
    CROSS_PRODUCT_OPPORTUNITY = "cross_product_opportunity"


class GoalStatus(StrEnum):
    """Lifecycle status for a goal proposal."""

    DRAFT = "draft"
    PROPOSED = "proposed"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    DEFERRED = "deferred"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    CANCELLED = "cancelled"


class GoalRiskLevel(StrEnum):
    """Risk level for a proposed change."""

    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


class EffortLevel(StrEnum):
    """Effort level for implementing a proposal."""

    TRIVIAL = "trivial"
    SMALL = "small"
    MEDIUM = "medium"
    LARGE = "large"
    MAJOR = "major"


class RiskAssessment(BaseModel):
    """Risk analysis for a goal proposal."""

    level: GoalRiskLevel = GoalRiskLevel.LOW
    blast_radius: str = ""
    reversible: bool = True
    safety_concerns: list[str] = Field(default_factory=list)
    mitigation_steps: list[str] = Field(default_factory=list)


class ImpactEstimate(BaseModel):
    """Expected impact of implementing a goal."""

    metric_name: str
    current_value: float
    expected_value: float
    improvement_pct: float = 0.0
    confidence: float = 0.5  # noqa: scanner: skip-magic


class GoalEvidence(BaseModel):
    """Evidence supporting a goal proposal."""

    pattern_ids: list[str] = Field(default_factory=list)
    workflow_ids: list[str] = Field(default_factory=list)
    metrics: dict[str, object] = Field(default_factory=dict)
    analysis_summary: str = ""


class GoalProposal(BaseModel):
    """A strategic goal proposal generated by an analyzer."""

    goal_type: GoalType
    title: str
    description: str
    risk_assessment: RiskAssessment = Field(default_factory=RiskAssessment)
    effort_estimate: EffortLevel = EffortLevel.MEDIUM
    expected_impacts: list[ImpactEstimate] = Field(default_factory=list)
    evidence: GoalEvidence = Field(default_factory=GoalEvidence)
    source_product_type: str | None = None
    applicable_product_types: list[str] = Field(default_factory=list)
    proposed_actions: list[str] = Field(default_factory=list)
    priority_score: float = 0.0
    source_agent_id: str | None = None  # M9: persistent agent that proposed this goal


class GoalReviewAction(StrEnum):
    """Actions available during goal review."""

    APPROVE = "approve"
    REJECT = "reject"
    DEFER = "defer"


class GoalReview(BaseModel):
    """A review decision on a goal proposal."""

    action: GoalReviewAction
    reviewer: str
    reason: str | None = None
    defer_until: str | None = None
