"""Constants for the agent registry module."""

STATUS_REGISTERED = "registered"
STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
VALID_STATUSES = frozenset({STATUS_REGISTERED, STATUS_ACTIVE, STATUS_INACTIVE})

PERSISTENT_NAMESPACE_PREFIX = "persistent__"
MAX_AGENT_NAME_LENGTH = 128
MAX_DESCRIPTION_LENGTH = 1024
DEFAULT_INVOCATION_TIMEOUT = 600  # seconds
