"""Constants for the memory module."""

PROVIDER_MEM0 = "mem0"
PROVIDER_IN_MEMORY = "in_memory"
PROVIDER_PG = "pg"
PROVIDER_KNOWLEDGE_GRAPH = "knowledge_graph"

MEMORY_TYPE_EPISODIC = "episodic"
MEMORY_TYPE_PROCEDURAL = "procedural"
MEMORY_TYPE_CROSS_SESSION = "cross_session"

DEFAULT_TENANT_ID = "default"
SCOPE_SEPARATOR = ":"

LATENCY_BUDGET_MS = 500
MAX_MEMORY_CONTEXT_CHARS = 4000
DEFAULT_RETRIEVAL_LIMIT = 5
MEMORY_QUERY_MAX_CHARS = 500
TRUNCATION_SUFFIX = "..."
TRUNCATION_SUFFIX_LEN = len(TRUNCATION_SUFFIX)
