"""Common constants used across the framework."""

# Probabilities and weights
# Time and durations
from src.constants.durations import (
    DAYS_PER_WEEK,
    DEFAULT_CACHE_TTL_SECONDS,
    DEFAULT_SESSION_TTL_SECONDS,
    DEFAULT_TIMEOUT_SECONDS,
    DEFAULT_TOKEN_TTL_SECONDS,
    HOURS_PER_DAY,
    MILLISECONDS_PER_SECOND,
    MINUTES_PER_HOUR,
    SECONDS_PER_DAY,
    SECONDS_PER_HOUR,
    SECONDS_PER_MINUTE,
    SECONDS_PER_WEEK,
    TIMEOUT_HTTP_DEFAULT,
    TTL_LONG,
    TTL_MEDIUM,
    TTL_SHORT,
)

# Limits and thresholds
from src.constants.limits import (
    DEFAULT_BATCH_SIZE,
    DEFAULT_MAX_ITEMS,
    DEFAULT_MAX_WORKERS,
    DEFAULT_PAGE_SIZE,
    DEFAULT_POOL_SIZE,
    MAX_WORKERS,
    PERCENT_10,
    PERCENT_20,
    PERCENT_50,
    PERCENT_75,
    PERCENT_90,
    PERCENT_95,
    THRESHOLD_LARGE_COUNT,
    THRESHOLD_MEDIUM_COUNT,
    THRESHOLD_SMALL_COUNT,
)
from src.constants.probabilities import (
    CONFIDENCE_HIGH,
    CONFIDENCE_LOW,
    CONFIDENCE_MEDIUM,
    CONFIDENCE_VERY_HIGH,
    CONFIDENCE_VERY_LOW,
    FRACTION_HALF,
    FRACTION_QUARTER,
    FRACTION_THIRD,
    FRACTION_THREE_QUARTERS,
    FRACTION_TWO_THIRDS,
    PROB_CRITICAL,
    PROB_HIGH,
    PROB_LOW,
    PROB_LOW_MEDIUM,
    PROB_MEDIUM,
    PROB_MEDIUM_HIGH,
    PROB_MEDIUM_LOW,
    PROB_MEDIUM_LOW_PLUS,
    PROB_MINIMAL,
    PROB_MODERATE,
    PROB_NEAR_CERTAIN,
    PROB_VERY_HIGH,
    PROB_VERY_HIGH_PLUS,
    PROB_VERY_LOW,
    TOLERANCE_LOOSE,
    TOLERANCE_NORMAL,
    TOLERANCE_TIGHT,
    TOLERANCE_VERY_LOOSE,
    TOLERANCE_VERY_TIGHT,
    WEIGHT_LARGE,
    WEIGHT_MEDIUM,
    WEIGHT_MINIMAL,
    WEIGHT_SMALL,
    WEIGHT_VERY_LARGE,
)

# Retries and backoff
from src.constants.retries import (
    CIRCUIT_BREAKER_FAILURE_THRESHOLD,
    CIRCUIT_BREAKER_RESET_TIMEOUT,
    DEFAULT_BACKOFF_MULTIPLIER,
    DEFAULT_MAX_RETRIES,
    DEFAULT_RETRY_BACKOFF_SECONDS,
    MAX_RETRY_ATTEMPTS,
    MIN_RETRY_ATTEMPTS,
    RETRY_JITTER_MAX,
    RETRY_JITTER_MIN,
)

# Sizes and buffers
from src.constants.sizes import (
    BUFFER_SIZE_LARGE,
    BUFFER_SIZE_MEDIUM,
    BUFFER_SIZE_SMALL,
    BYTES_PER_GB,
    BYTES_PER_KB,
    BYTES_PER_MB,
    BYTES_PER_TB,
    SIZE_1GB,
    SIZE_1KB,
    SIZE_1MB,
    SIZE_4KB,
    SIZE_10MB,
    SIZE_100MB,
    UUID_HEX_SHORT_LENGTH,
)

__all__ = [
    # Probabilities
    "PROB_MINIMAL",
    "PROB_VERY_LOW",
    "PROB_LOW",
    "PROB_MEDIUM",
    "PROB_HIGH",
    "PROB_VERY_HIGH",
    "PROB_CRITICAL",
    "PROB_NEAR_CERTAIN",
    "WEIGHT_SMALL",
    "WEIGHT_MEDIUM",
    "WEIGHT_LARGE",
    # Durations
    "SECONDS_PER_MINUTE",
    "SECONDS_PER_HOUR",
    "SECONDS_PER_DAY",
    "DEFAULT_CACHE_TTL_SECONDS",
    "DEFAULT_SESSION_TTL_SECONDS",
    # Sizes
    "BYTES_PER_KB",
    "BYTES_PER_MB",
    "BYTES_PER_GB",
    # Retries
    "DEFAULT_MAX_RETRIES",
    "DEFAULT_BACKOFF_MULTIPLIER",
    # Limits
    "DEFAULT_MAX_ITEMS",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_POOL_SIZE",
]
