"""Phase 6: Catch up schema drift

Revision ID: 99c79410e449
Revises: 9bba5a67eb64
Create Date: 2026-02-07 13:21:02.897988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '99c79410e449'
down_revision: Union[str, Sequence[str], None] = '9bba5a67eb64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'STOPPED', 'COMPLETED', name='experimentstatus'), nullable=False),
    sa.Column('assignment_strategy', sa.Enum('RANDOM', 'HASH', 'STRATIFIED', 'BANDIT', name='assignmentstrategytype'), nullable=False),
    sa.Column('traffic_allocation', sa.JSON(), nullable=True),
    sa.Column('primary_metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_metrics', sa.JSON(), nullable=True),
    sa.Column('guardrail_metrics', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('min_sample_size_per_variant', sa.Integer(), nullable=False),
    sa.Column('winner_variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('winning_confidence', sa.Float(), nullable=True),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiment_status_created', 'experiments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_experiments_created_at'), 'experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=True)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('m5_loop_state',
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('phase_data', sa.JSON(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_name')
    )
    op.create_table('experiment_results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('variant_metrics', sa.JSON(), nullable=True),
    sa.Column('statistical_tests', sa.JSON(), nullable=True),
    sa.Column('guardrail_violations', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Enum('CONTINUE', 'STOP_WINNER', 'STOP_NO_DIFFERENCE', 'STOP_GUARDRAIL_VIOLATION', name='recommendationtype'), nullable=False),
    sa.Column('recommended_winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_experiment_analyzed', 'experiment_results', ['experiment_id', 'analyzed_at'], unique=False)
    op.create_index(op.f('ix_experiment_results_analyzed_at'), 'experiment_results', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_experiment_results_experiment_id'), 'experiment_results', ['experiment_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('config_type', sa.Enum('AGENT', 'STAGE', 'WORKFLOW', 'PROMPT', name='configtype'), nullable=False),
    sa.Column('config_overrides', sa.JSON(), nullable=True),
    sa.Column('allocated_traffic', sa.Float(), nullable=False),
    sa.Column('actual_traffic', sa.Float(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_variant_experiment_name', 'variants', ['experiment_id', 'name'], unique=False)
    op.create_index(op.f('ix_variants_experiment_id'), 'variants', ['experiment_id'], unique=False)
    op.create_table('variant_assignments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('workflow_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assignment_strategy', sa.Enum('RANDOM', 'HASH', 'STRATIFIED', 'BANDIT', name='assignmentstrategytype'), nullable=False),
    sa.Column('assignment_context', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_experiment_variant', 'variant_assignments', ['experiment_id', 'variant_id'], unique=False)
    op.create_index('idx_assignment_status_completed', 'variant_assignments', ['execution_status', 'execution_completed_at'], unique=False)
    op.create_index(op.f('ix_variant_assignments_assigned_at'), 'variant_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_variant_assignments_execution_status'), 'variant_assignments', ['execution_status'], unique=False)
    op.create_index(op.f('ix_variant_assignments_experiment_id'), 'variant_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_variant_assignments_variant_id'), 'variant_assignments', ['variant_id'], unique=False)
    op.create_index(op.f('ix_variant_assignments_workflow_execution_id'), 'variant_assignments', ['workflow_execution_id'], unique=True)
    op.add_column('agent_merit_scores', sa.Column('mixed_decisions', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_merit_agent_domain', 'agent_merit_scores', ['agent_name', 'domain'])
    op.create_index('idx_outcome_validation_ts', 'decision_outcomes', ['validation_timestamp'], unique=False)
    op.alter_column('m5_experiment_results', 'id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('m5_experiment_results', 'experiment_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'variant_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'execution_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'quality_score',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('m5_experiment_results', 'speed_seconds',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('m5_experiment_results', 'cost_usd',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('m5_experiment_results', 'recorded_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'extra_metrics',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(None, 'm5_experiment_results', type_='foreignkey')
    op.create_foreign_key(None, 'm5_experiment_results', 'm5_experiments', ['experiment_id'], ['id'], ondelete='CASCADE')
    op.alter_column('m5_experiments', 'id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               nullable=False)
    op.alter_column('m5_experiments', 'agent_name',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'status',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'control_config',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'variant_configs',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'target_samples_per_variant',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(50)'))
    op.alter_column('m5_experiments', 'winner_variant_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'analysis_results',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'proposal_id',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'completed_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'extra_metadata',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index('idx_rollback_snapshots_expires', 'rollback_snapshots', ['expires_at'], unique=False)
    op.create_index('idx_tool_approval', 'tool_executions', ['approval_required'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tool_approval', table_name='tool_executions')
    op.drop_index('idx_rollback_snapshots_expires', table_name='rollback_snapshots')
    op.alter_column('m5_experiments', 'extra_metadata',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'completed_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'proposal_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'analysis_results',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'winner_variant_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('m5_experiments', 'target_samples_per_variant',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(50)'))
    op.alter_column('m5_experiments', 'variant_configs',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'control_config',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'status',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'agent_name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiments', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_constraint(None, 'm5_experiment_results', type_='foreignkey')
    op.create_foreign_key(None, 'm5_experiment_results', 'm5_experiments', ['experiment_id'], ['id'])
    op.alter_column('m5_experiment_results', 'extra_metrics',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('m5_experiment_results', 'recorded_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'cost_usd',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('m5_experiment_results', 'speed_seconds',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('m5_experiment_results', 'quality_score',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('m5_experiment_results', 'execution_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'variant_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'experiment_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('m5_experiment_results', 'id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_index('idx_outcome_validation_ts', table_name='decision_outcomes')
    op.drop_constraint('uq_merit_agent_domain', 'agent_merit_scores', type_='unique')
    op.drop_column('agent_merit_scores', 'mixed_decisions')
    op.drop_index(op.f('ix_variant_assignments_workflow_execution_id'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_variant_id'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_experiment_id'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_execution_status'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_assigned_at'), table_name='variant_assignments')
    op.drop_index('idx_assignment_status_completed', table_name='variant_assignments')
    op.drop_index('idx_assignment_experiment_variant', table_name='variant_assignments')
    op.drop_table('variant_assignments')
    op.drop_index(op.f('ix_variants_experiment_id'), table_name='variants')
    op.drop_index('idx_variant_experiment_name', table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_experiment_results_experiment_id'), table_name='experiment_results')
    op.drop_index(op.f('ix_experiment_results_analyzed_at'), table_name='experiment_results')
    op.drop_index('idx_result_experiment_analyzed', table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_table('m5_loop_state')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_at'), table_name='experiments')
    op.drop_index('idx_experiment_status_created', table_name='experiments')
    op.drop_table('experiments')
    # ### end Alembic commands ###
