"""Phase 1 model changes: constraints, cascades, mixed_decisions

Phase 1 audit remediation:
- Add mixed_decisions column to agent_merit_scores
- Add UniqueConstraint(agent_name, domain) to agent_merit_scores
- Add CheckConstraint to 7 observability models (status validation)
- Create new tables: experiments, variants, variant_assignments,
  experiment_results, m5_experiments, m5_experiment_results,
  m5_loop_state, custom_metrics (all with CASCADE FK + constraints)

Note: SQLite does not support ALTER TABLE ADD CONSTRAINT. CHECK constraints
on existing tables are added via batch_alter_table which recreates the table.
For PostgreSQL deployments, standard ALTER TABLE is used.

Revision ID: 9bba5a67eb64
Revises: abd552d7a52e
Create Date: 2026-02-06 23:59:26.389236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '9bba5a67eb64'
down_revision: Union[str, Sequence[str], None] = 'abd552d7a52e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ---- Phase 1: CHECK constraints on existing tables ----
    # These constraints validate status columns to prevent invalid data.
    # Using batch mode for SQLite compatibility (table recreation).

    with op.batch_alter_table('workflow_executions') as batch_op:
        batch_op.create_check_constraint(
            'wf_valid_status',
            "status IN ('running', 'completed', 'failed', 'halted', 'timeout')",
        )

    with op.batch_alter_table('stage_executions') as batch_op:
        batch_op.create_check_constraint(
            'stage_valid_status',
            "status IN ('running', 'completed', 'failed', 'halted', 'timeout')",
        )

    with op.batch_alter_table('agent_executions') as batch_op:
        batch_op.create_check_constraint(
            'agent_valid_status',
            "status IN ('running', 'completed', 'failed', 'halted', 'timeout')",
        )

    with op.batch_alter_table('llm_calls') as batch_op:
        batch_op.create_check_constraint(
            'llm_valid_status',
            "status IN ('success', 'error', 'timeout', 'cancelled')",
        )

    with op.batch_alter_table('tool_executions') as batch_op:
        batch_op.create_check_constraint(
            'tool_valid_status',
            "status IN ('success', 'error', 'timeout', 'cancelled')",
        )

    with op.batch_alter_table('rollback_events') as batch_op:
        batch_op.create_check_constraint(
            'rollback_valid_status',
            "status IN ('completed', 'partial', 'failed')",
        )

    with op.batch_alter_table('decision_outcomes') as batch_op:
        batch_op.create_check_constraint(
            'outcome_valid_value',
            "outcome IN ('success', 'failure', 'neutral', 'mixed')",
        )

    # ---- Phase 1: New tables ----
    op.create_table('custom_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('metric_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collector_version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_metrics_collected_at'), 'custom_metrics', ['collected_at'], unique=False)
    op.create_index('ix_custom_metrics_execution_collected', 'custom_metrics', ['execution_id', 'collected_at'], unique=False)
    op.create_index(op.f('ix_custom_metrics_execution_id'), 'custom_metrics', ['execution_id'], unique=False)
    op.create_index('ix_custom_metrics_metric_collected', 'custom_metrics', ['metric_name', 'collected_at'], unique=False)
    op.create_index(op.f('ix_custom_metrics_metric_name'), 'custom_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_custom_metrics_metric_type'), 'custom_metrics', ['metric_type'], unique=False)
    op.create_index('ix_custom_metrics_type_collected', 'custom_metrics', ['metric_type', 'collected_at'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'PAUSED', 'STOPPED', 'COMPLETED', name='experimentstatus'), nullable=False),
    sa.Column('assignment_strategy', sa.Enum('RANDOM', 'HASH', 'STRATIFIED', 'BANDIT', name='assignmentstrategytype'), nullable=False),
    sa.Column('traffic_allocation', sa.JSON(), nullable=True),
    sa.Column('primary_metric', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_metrics', sa.JSON(), nullable=True),
    sa.Column('guardrail_metrics', sa.JSON(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=False),
    sa.Column('min_sample_size_per_variant', sa.Integer(), nullable=False),
    sa.Column('winner_variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('winning_confidence', sa.Float(), nullable=True),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_experiment_status_created', 'experiments', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_experiments_created_at'), 'experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_experiments_name'), 'experiments', ['name'], unique=True)
    op.create_index(op.f('ix_experiments_status'), 'experiments', ['status'], unique=False)
    op.create_table('m5_experiments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('control_config', sa.JSON(), nullable=False),
    sa.Column('variant_configs', sa.JSON(), nullable=False),
    sa.Column('target_samples_per_variant', sa.Integer(), nullable=False),
    sa.Column('winner_variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('analysis_results', sa.JSON(), nullable=True),
    sa.Column('proposal_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_m5_exp_agent', 'm5_experiments', ['agent_name'], unique=False)
    op.create_index('idx_m5_exp_status', 'm5_experiments', ['status'], unique=False)
    op.create_table('m5_loop_state',
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_phase', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('iteration_number', sa.Integer(), nullable=False),
    sa.Column('phase_data', sa.JSON(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('agent_name')
    )
    op.create_table('experiment_results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('variant_metrics', sa.JSON(), nullable=True),
    sa.Column('statistical_tests', sa.JSON(), nullable=True),
    sa.Column('guardrail_violations', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.Enum('CONTINUE', 'STOP_WINNER', 'STOP_NO_DIFFERENCE', 'STOP_GUARDRAIL_VIOLATION', name='recommendationtype'), nullable=False),
    sa.Column('recommended_winner', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_result_experiment_analyzed', 'experiment_results', ['experiment_id', 'analyzed_at'], unique=False)
    op.create_index(op.f('ix_experiment_results_analyzed_at'), 'experiment_results', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_experiment_results_experiment_id'), 'experiment_results', ['experiment_id'], unique=False)
    op.create_table('m5_experiment_results',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=False),
    sa.Column('variant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('speed_seconds', sa.Float(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['m5_experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id')
    )
    op.create_index('idx_m5_result_experiment', 'm5_experiment_results', ['experiment_id'], unique=False)
    op.create_index('idx_m5_result_variant', 'm5_experiment_results', ['variant_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_control', sa.Boolean(), nullable=False),
    sa.Column('config_type', sa.Enum('AGENT', 'STAGE', 'WORKFLOW', 'PROMPT', name='configtype'), nullable=False),
    sa.Column('config_overrides', sa.JSON(), nullable=True),
    sa.Column('allocated_traffic', sa.Float(), nullable=False),
    sa.Column('actual_traffic', sa.Float(), nullable=False),
    sa.Column('total_executions', sa.Integer(), nullable=False),
    sa.Column('successful_executions', sa.Integer(), nullable=False),
    sa.Column('failed_executions', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_variant_experiment_name', 'variants', ['experiment_id', 'name'], unique=False)
    op.create_index(op.f('ix_variants_experiment_id'), 'variants', ['experiment_id'], unique=False)
    op.create_table('variant_assignments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('experiment_id', sa.String(), nullable=True),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('workflow_execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assignment_strategy', sa.Enum('RANDOM', 'HASH', 'STRATIFIED', 'BANDIT', name='assignmentstrategytype'), nullable=False),
    sa.Column('assignment_context', sa.JSON(), nullable=True),
    sa.Column('execution_status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', name='executionstatus'), nullable=False),
    sa.Column('execution_started_at', sa.DateTime(), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_assignment_experiment_variant', 'variant_assignments', ['experiment_id', 'variant_id'], unique=False)
    op.create_index('idx_assignment_status_completed', 'variant_assignments', ['execution_status', 'execution_completed_at'], unique=False)
    op.create_index(op.f('ix_variant_assignments_assigned_at'), 'variant_assignments', ['assigned_at'], unique=False)
    op.create_index(op.f('ix_variant_assignments_execution_status'), 'variant_assignments', ['execution_status'], unique=False)
    op.create_index(op.f('ix_variant_assignments_experiment_id'), 'variant_assignments', ['experiment_id'], unique=False)
    op.create_index(op.f('ix_variant_assignments_variant_id'), 'variant_assignments', ['variant_id'], unique=False)
    op.create_index(op.f('ix_variant_assignments_workflow_execution_id'), 'variant_assignments', ['workflow_execution_id'], unique=True)
    # Use batch mode for SQLite compatibility: add column + unique constraint together.
    # server_default='0' ensures existing rows get a valid value.
    with op.batch_alter_table('agent_merit_scores') as batch_op:
        batch_op.add_column(sa.Column('mixed_decisions', sa.Integer(), nullable=False, server_default='0'))
        batch_op.create_unique_constraint('uq_merit_agent_domain', ['agent_name', 'domain'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # ---- Reverse Phase 1: CHECK constraints ----
    with op.batch_alter_table('decision_outcomes') as batch_op:
        batch_op.drop_constraint('outcome_valid_value', type_='check')

    with op.batch_alter_table('rollback_events') as batch_op:
        batch_op.drop_constraint('rollback_valid_status', type_='check')

    with op.batch_alter_table('tool_executions') as batch_op:
        batch_op.drop_constraint('tool_valid_status', type_='check')

    with op.batch_alter_table('llm_calls') as batch_op:
        batch_op.drop_constraint('llm_valid_status', type_='check')

    with op.batch_alter_table('agent_executions') as batch_op:
        batch_op.drop_constraint('agent_valid_status', type_='check')

    with op.batch_alter_table('stage_executions') as batch_op:
        batch_op.drop_constraint('stage_valid_status', type_='check')

    with op.batch_alter_table('workflow_executions') as batch_op:
        batch_op.drop_constraint('wf_valid_status', type_='check')

    # ---- Reverse Phase 1: column + constraint changes ----
    with op.batch_alter_table('agent_merit_scores') as batch_op:
        batch_op.drop_constraint('uq_merit_agent_domain', type_='unique')
        batch_op.drop_column('mixed_decisions')
    op.drop_index(op.f('ix_variant_assignments_workflow_execution_id'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_variant_id'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_experiment_id'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_execution_status'), table_name='variant_assignments')
    op.drop_index(op.f('ix_variant_assignments_assigned_at'), table_name='variant_assignments')
    op.drop_index('idx_assignment_status_completed', table_name='variant_assignments')
    op.drop_index('idx_assignment_experiment_variant', table_name='variant_assignments')
    op.drop_table('variant_assignments')
    op.drop_index(op.f('ix_variants_experiment_id'), table_name='variants')
    op.drop_index('idx_variant_experiment_name', table_name='variants')
    op.drop_table('variants')
    op.drop_index('idx_m5_result_variant', table_name='m5_experiment_results')
    op.drop_index('idx_m5_result_experiment', table_name='m5_experiment_results')
    op.drop_table('m5_experiment_results')
    op.drop_index(op.f('ix_experiment_results_experiment_id'), table_name='experiment_results')
    op.drop_index(op.f('ix_experiment_results_analyzed_at'), table_name='experiment_results')
    op.drop_index('idx_result_experiment_analyzed', table_name='experiment_results')
    op.drop_table('experiment_results')
    op.drop_table('m5_loop_state')
    op.drop_index('idx_m5_exp_status', table_name='m5_experiments')
    op.drop_index('idx_m5_exp_agent', table_name='m5_experiments')
    op.drop_table('m5_experiments')
    op.drop_index(op.f('ix_experiments_status'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_name'), table_name='experiments')
    op.drop_index(op.f('ix_experiments_created_at'), table_name='experiments')
    op.drop_index('idx_experiment_status_created', table_name='experiments')
    op.drop_table('experiments')
    op.drop_index('ix_custom_metrics_type_collected', table_name='custom_metrics')
    op.drop_index(op.f('ix_custom_metrics_metric_type'), table_name='custom_metrics')
    op.drop_index(op.f('ix_custom_metrics_metric_name'), table_name='custom_metrics')
    op.drop_index('ix_custom_metrics_metric_collected', table_name='custom_metrics')
    op.drop_index(op.f('ix_custom_metrics_execution_id'), table_name='custom_metrics')
    op.drop_index('ix_custom_metrics_execution_collected', table_name='custom_metrics')
    op.drop_index(op.f('ix_custom_metrics_collected_at'), table_name='custom_metrics')
    op.drop_table('custom_metrics')
    # ### end Alembic commands ###
