"""initial schema

Revision ID: abd552d7a52e
Revises: 
Create Date: 2026-02-04 20:47:17.705990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'abd552d7a52e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_merit_scores',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_decisions', sa.Integer(), nullable=False),
    sa.Column('successful_decisions', sa.Integer(), nullable=False),
    sa.Column('failed_decisions', sa.Integer(), nullable=False),
    sa.Column('overridden_decisions', sa.Integer(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_confidence', sa.Float(), nullable=True),
    sa.Column('expertise_score', sa.Float(), nullable=True),
    sa.Column('last_30_days_success_rate', sa.Float(), nullable=True),
    sa.Column('last_90_days_success_rate', sa.Float(), nullable=True),
    sa.Column('first_decision_date', sa.DateTime(), nullable=True),
    sa.Column('last_decision_date', sa.DateTime(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_merit_agent', 'agent_merit_scores', ['agent_name', 'domain'], unique=False)
    op.create_index(op.f('ix_agent_merit_scores_agent_name'), 'agent_merit_scores', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_merit_scores_domain'), 'agent_merit_scores', ['domain'], unique=False)
    op.create_table('schema_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schema_version_version'), 'schema_version', ['version'], unique=True)
    op.create_table('system_metrics',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('aggregation_period', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_metrics_name', 'system_metrics', ['metric_name', 'timestamp'], unique=False)
    op.create_index('idx_metrics_workflow', 'system_metrics', ['workflow_name', 'timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_metric_name'), 'system_metrics', ['metric_name'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_workflow_name'), 'system_metrics', ['workflow_name'], unique=False)
    op.create_table('workflow_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workflow_config_snapshot', sa.JSON(), nullable=True),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('trigger_data', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_stack_trace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('optimization_target', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('product_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('environment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_cost_usd', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('total_llm_calls', sa.Integer(), nullable=True),
    sa.Column('total_tool_calls', sa.Integer(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_end_time', 'workflow_executions', ['end_time'], unique=False)
    op.create_index('idx_workflow_name', 'workflow_executions', ['workflow_name', 'start_time'], unique=False)
    op.create_index('idx_workflow_status', 'workflow_executions', ['status', 'start_time'], unique=False)
    op.create_index(op.f('ix_workflow_executions_status'), 'workflow_executions', ['status'], unique=False)
    op.create_index(op.f('ix_workflow_executions_workflow_name'), 'workflow_executions', ['workflow_name'], unique=False)
    op.create_table('rollback_snapshots',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_execution_id', sa.String(), nullable=True),
    sa.Column('checkpoint_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sa.JSON(), nullable=True),
    sa.Column('context', sa.JSON(), nullable=True),
    sa.Column('file_snapshots', sa.JSON(), nullable=True),
    sa.Column('state_snapshots', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rollback_snapshots_expires', 'rollback_snapshots', ['expires_at'], unique=False)
    op.create_index('idx_rollback_snapshots_workflow', 'rollback_snapshots', ['workflow_execution_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_rollback_snapshots_created_at'), 'rollback_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_rollback_snapshots_workflow_execution_id'), 'rollback_snapshots', ['workflow_execution_id'], unique=False)
    op.create_table('stage_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workflow_execution_id', sa.String(), nullable=True),
    sa.Column('stage_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('stage_config_snapshot', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('num_agents_executed', sa.Integer(), nullable=True),
    sa.Column('num_agents_succeeded', sa.Integer(), nullable=True),
    sa.Column('num_agents_failed', sa.Integer(), nullable=True),
    sa.Column('collaboration_rounds', sa.Integer(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_stage_end_time', 'stage_executions', ['end_time'], unique=False)
    op.create_index('idx_stage_status', 'stage_executions', ['status', 'start_time'], unique=False)
    op.create_index('idx_stage_workflow', 'stage_executions', ['workflow_execution_id', 'stage_name'], unique=False)
    op.create_index(op.f('ix_stage_executions_stage_name'), 'stage_executions', ['stage_name'], unique=False)
    op.create_index(op.f('ix_stage_executions_status'), 'stage_executions', ['status'], unique=False)
    op.create_index(op.f('ix_stage_executions_workflow_execution_id'), 'stage_executions', ['workflow_execution_id'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_execution_id', sa.String(), nullable=True),
    sa.Column('agent_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_config_snapshot', sa.JSON(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('llm_duration_seconds', sa.Float(), nullable=True),
    sa.Column('tool_duration_seconds', sa.Float(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('num_llm_calls', sa.Integer(), nullable=True),
    sa.Column('num_tool_calls', sa.Integer(), nullable=True),
    sa.Column('votes_cast', sa.JSON(), nullable=True),
    sa.Column('conflicts_with_agents', sa.JSON(), nullable=True),
    sa.Column('final_decision', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('output_quality_score', sa.Float(), nullable=True),
    sa.Column('reasoning_quality_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_end_time', 'agent_executions', ['end_time'], unique=False)
    op.create_index('idx_agent_name', 'agent_executions', ['agent_name', 'start_time'], unique=False)
    op.create_index('idx_agent_stage', 'agent_executions', ['stage_execution_id', 'agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_agent_name'), 'agent_executions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_stage_execution_id'), 'agent_executions', ['stage_execution_id'], unique=False)
    op.create_index(op.f('ix_agent_executions_status'), 'agent_executions', ['status'], unique=False)
    op.create_table('collaboration_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stage_execution_id', sa.String(), nullable=True),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('agents_involved', sa.JSON(), nullable=True),
    sa.Column('event_data', sa.JSON(), nullable=True),
    sa.Column('resolution_strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_collab_stage', 'collaboration_events', ['stage_execution_id', 'event_type'], unique=False)
    op.create_index(op.f('ix_collaboration_events_event_type'), 'collaboration_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_collaboration_events_stage_execution_id'), 'collaboration_events', ['stage_execution_id'], unique=False)
    op.create_table('rollback_events',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('snapshot_id', sa.String(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('operator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reverted_items', sa.JSON(), nullable=True),
    sa.Column('failed_items', sa.JSON(), nullable=True),
    sa.Column('errors', sa.JSON(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rollback_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['snapshot_id'], ['rollback_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rollback_events_snapshot', 'rollback_events', ['snapshot_id', 'executed_at'], unique=False)
    op.create_index('idx_rollback_events_trigger', 'rollback_events', ['trigger', 'executed_at'], unique=False)
    op.create_index(op.f('ix_rollback_events_executed_at'), 'rollback_events', ['executed_at'], unique=False)
    op.create_index(op.f('ix_rollback_events_snapshot_id'), 'rollback_events', ['snapshot_id'], unique=False)
    op.create_index(op.f('ix_rollback_events_status'), 'rollback_events', ['status'], unique=False)
    op.create_index(op.f('ix_rollback_events_trigger'), 'rollback_events', ['trigger'], unique=False)
    op.create_table('decision_outcomes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_execution_id', sa.String(), nullable=True),
    sa.Column('stage_execution_id', sa.String(), nullable=True),
    sa.Column('workflow_execution_id', sa.String(), nullable=True),
    sa.Column('decision_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('decision_data', sa.JSON(), nullable=True),
    sa.Column('validation_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('validation_timestamp', sa.DateTime(), nullable=True),
    sa.Column('validation_duration_seconds', sa.Float(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('impact_metrics', sa.JSON(), nullable=True),
    sa.Column('lessons_learned', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('should_repeat', sa.Boolean(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_execution_id'], ['stage_executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_execution_id'], ['workflow_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outcome_agent', 'decision_outcomes', ['agent_execution_id', 'outcome'], unique=False)
    op.create_index('idx_outcome_type', 'decision_outcomes', ['decision_type', 'outcome'], unique=False)
    op.create_index('idx_outcome_validation_ts', 'decision_outcomes', ['validation_timestamp'], unique=False)
    op.create_index(op.f('ix_decision_outcomes_decision_type'), 'decision_outcomes', ['decision_type'], unique=False)
    op.create_index(op.f('ix_decision_outcomes_outcome'), 'decision_outcomes', ['outcome'], unique=False)
    op.create_table('llm_calls',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_execution_id', sa.String(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('top_p', sa.Float(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_llm_agent', 'llm_calls', ['agent_execution_id', 'start_time'], unique=False)
    op.create_index('idx_llm_model', 'llm_calls', ['model', 'start_time'], unique=False)
    op.create_index('idx_llm_status', 'llm_calls', ['status', 'start_time'], unique=False)
    op.create_index(op.f('ix_llm_calls_agent_execution_id'), 'llm_calls', ['agent_execution_id'], unique=False)
    op.create_index(op.f('ix_llm_calls_model'), 'llm_calls', ['model'], unique=False)
    op.create_index(op.f('ix_llm_calls_provider'), 'llm_calls', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_calls_status'), 'llm_calls', ['status'], unique=False)
    op.create_table('tool_executions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_execution_id', sa.String(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tool_version', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('input_params', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('safety_checks_applied', sa.JSON(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('approval_timestamp', sa.DateTime(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_execution_id'], ['agent_executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tool_agent', 'tool_executions', ['agent_execution_id', 'tool_name'], unique=False)
    op.create_index('idx_tool_approval', 'tool_executions', ['approval_required'], unique=False)
    op.create_index('idx_tool_name', 'tool_executions', ['tool_name', 'start_time'], unique=False)
    op.create_index('idx_tool_status', 'tool_executions', ['status', 'start_time'], unique=False)
    op.create_index(op.f('ix_tool_executions_agent_execution_id'), 'tool_executions', ['agent_execution_id'], unique=False)
    op.create_index(op.f('ix_tool_executions_status'), 'tool_executions', ['status'], unique=False)
    op.create_index(op.f('ix_tool_executions_tool_name'), 'tool_executions', ['tool_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tool_executions_tool_name'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_status'), table_name='tool_executions')
    op.drop_index(op.f('ix_tool_executions_agent_execution_id'), table_name='tool_executions')
    op.drop_index('idx_tool_status', table_name='tool_executions')
    op.drop_index('idx_tool_name', table_name='tool_executions')
    op.drop_index('idx_tool_approval', table_name='tool_executions')
    op.drop_index('idx_tool_agent', table_name='tool_executions')
    op.drop_table('tool_executions')
    op.drop_index(op.f('ix_llm_calls_status'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_provider'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_model'), table_name='llm_calls')
    op.drop_index(op.f('ix_llm_calls_agent_execution_id'), table_name='llm_calls')
    op.drop_index('idx_llm_status', table_name='llm_calls')
    op.drop_index('idx_llm_model', table_name='llm_calls')
    op.drop_index('idx_llm_agent', table_name='llm_calls')
    op.drop_table('llm_calls')
    op.drop_index(op.f('ix_decision_outcomes_outcome'), table_name='decision_outcomes')
    op.drop_index(op.f('ix_decision_outcomes_decision_type'), table_name='decision_outcomes')
    op.drop_index('idx_outcome_validation_ts', table_name='decision_outcomes')
    op.drop_index('idx_outcome_type', table_name='decision_outcomes')
    op.drop_index('idx_outcome_agent', table_name='decision_outcomes')
    op.drop_table('decision_outcomes')
    op.drop_index(op.f('ix_rollback_events_trigger'), table_name='rollback_events')
    op.drop_index(op.f('ix_rollback_events_status'), table_name='rollback_events')
    op.drop_index(op.f('ix_rollback_events_snapshot_id'), table_name='rollback_events')
    op.drop_index(op.f('ix_rollback_events_executed_at'), table_name='rollback_events')
    op.drop_index('idx_rollback_events_trigger', table_name='rollback_events')
    op.drop_index('idx_rollback_events_snapshot', table_name='rollback_events')
    op.drop_table('rollback_events')
    op.drop_index(op.f('ix_collaboration_events_stage_execution_id'), table_name='collaboration_events')
    op.drop_index(op.f('ix_collaboration_events_event_type'), table_name='collaboration_events')
    op.drop_index('idx_collab_stage', table_name='collaboration_events')
    op.drop_table('collaboration_events')
    op.drop_index(op.f('ix_agent_executions_status'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_stage_execution_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_name'), table_name='agent_executions')
    op.drop_index('idx_agent_stage', table_name='agent_executions')
    op.drop_index('idx_agent_name', table_name='agent_executions')
    op.drop_index('idx_agent_end_time', table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_stage_executions_workflow_execution_id'), table_name='stage_executions')
    op.drop_index(op.f('ix_stage_executions_status'), table_name='stage_executions')
    op.drop_index(op.f('ix_stage_executions_stage_name'), table_name='stage_executions')
    op.drop_index('idx_stage_workflow', table_name='stage_executions')
    op.drop_index('idx_stage_status', table_name='stage_executions')
    op.drop_index('idx_stage_end_time', table_name='stage_executions')
    op.drop_table('stage_executions')
    op.drop_index(op.f('ix_rollback_snapshots_workflow_execution_id'), table_name='rollback_snapshots')
    op.drop_index(op.f('ix_rollback_snapshots_created_at'), table_name='rollback_snapshots')
    op.drop_index('idx_rollback_snapshots_workflow', table_name='rollback_snapshots')
    op.drop_index('idx_rollback_snapshots_expires', table_name='rollback_snapshots')
    op.drop_table('rollback_snapshots')
    op.drop_index(op.f('ix_workflow_executions_workflow_name'), table_name='workflow_executions')
    op.drop_index(op.f('ix_workflow_executions_status'), table_name='workflow_executions')
    op.drop_index('idx_workflow_status', table_name='workflow_executions')
    op.drop_index('idx_workflow_name', table_name='workflow_executions')
    op.drop_index('idx_workflow_end_time', table_name='workflow_executions')
    op.drop_table('workflow_executions')
    op.drop_index(op.f('ix_system_metrics_workflow_name'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index(op.f('ix_system_metrics_metric_name'), table_name='system_metrics')
    op.drop_index('idx_metrics_workflow', table_name='system_metrics')
    op.drop_index('idx_metrics_name', table_name='system_metrics')
    op.drop_table('system_metrics')
    op.drop_index(op.f('ix_schema_version_version'), table_name='schema_version')
    op.drop_table('schema_version')
    op.drop_index(op.f('ix_agent_merit_scores_domain'), table_name='agent_merit_scores')
    op.drop_index(op.f('ix_agent_merit_scores_agent_name'), table_name='agent_merit_scores')
    op.drop_index('idx_merit_agent', table_name='agent_merit_scores')
    op.drop_table('agent_merit_scores')
    # ### end Alembic commands ###
