"""Constants for the autonomous loop module."""

DEFAULT_LOOKBACK_HOURS = 24
LOOP_TIMEOUT_SECONDS = 300
MS_PER_SECOND = 1000
DEFAULT_AUTO_APPLY_MIN_CONFIDENCE = 0.8
DEFAULT_MAX_AUTO_APPLY_PER_RUN = 5

# Rollout phases — traffic percentages for gradual rollout
ROLLOUT_PHASE_CANARY = 10
ROLLOUT_PHASE_PARTIAL = 25
ROLLOUT_PHASE_MAJORITY = 50
ROLLOUT_PHASE_FULL = 100
DEFAULT_ROLLOUT_PHASES = [
    ROLLOUT_PHASE_CANARY,
    ROLLOUT_PHASE_PARTIAL,
    ROLLOUT_PHASE_MAJORITY,
    ROLLOUT_PHASE_FULL,
]
