"""Common limits, thresholds, and capacity constants.

These constants define various system limits and boundaries.
"""

# LLM Model Defaults (cross-cutting, used by agents + cache layers)
DEFAULT_TEMPERATURE = 0.7
DEFAULT_MAX_TOKENS = 131072

# Item/collection limits
DEFAULT_MAX_ITEMS = 10
DEFAULT_MIN_ITEMS = 1
SMALL_ITEM_LIMIT = 5
MEDIUM_ITEM_LIMIT = 10
LARGE_ITEM_LIMIT = 50
VERY_LARGE_ITEM_LIMIT = 100

# Batch and page sizes
DEFAULT_BATCH_SIZE = 50

# Worker and connection pools
DEFAULT_POOL_SIZE = 50
SMALL_POOL_SIZE = 10
MAX_WORKERS = 10000
DEFAULT_MAX_WORKERS = 100
MIN_WORKERS = 1

# Queue and buffer limits
DEFAULT_QUEUE_SIZE = 1000
SMALL_QUEUE_SIZE = 100
MAX_QUEUE_SIZE = 100000

# Count thresholds
THRESHOLD_MIN_COUNT = 1
THRESHOLD_SMALL_COUNT = 5
THRESHOLD_MEDIUM_COUNT = 10
THRESHOLD_LARGE_COUNT = 100
THRESHOLD_VERY_LARGE_COUNT = 1000
THRESHOLD_MASSIVE_COUNT = 10000

# Percentage thresholds
PERCENT_20 = 20
PERCENT_50 = 50
PERCENT_80 = 80
PERCENT_95 = 95
PERCENT_99 = 99
PERCENT_100 = 100

# Path limits (POSIX)
MAX_PATH_LENGTH = 4096  # Typical Linux PATH_MAX
MAX_COMPONENT_LENGTH = 255  # Typical NAME_MAX

# String length limits
MAX_SHORT_STRING_LENGTH = 255
MAX_MEDIUM_STRING_LENGTH = 500
MAX_LONG_STRING_LENGTH = 1000
MAX_TEXT_LENGTH = 10000

# Common multipliers
MULTIPLIER_SMALL = 2
MULTIPLIER_MEDIUM = 10
MULTIPLIER_LARGE = 100
MULTIPLIER_VERY_LARGE = 1000
