#!/usr/bin/env python3
"""
Auto-generate developer documentation for all registered tools.

Discovers tools via ToolRegistry.auto_discover(), extracts metadata,
parameter schemas, config schemas, and result schemas, then renders
markdown (or JSON) documentation.

Usage:
    python scripts/generate_tool_docs.py                          # default markdown output
    python scripts/generate_tool_docs.py --output docs/tools/     # custom output dir
    python scripts/generate_tool_docs.py --format json            # JSON dump
    python scripts/generate_tool_docs.py --check                  # CI validation (exit 1 if stale)
"""

from __future__ import annotations

import argparse
import json
import sys
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# Ensure the project root is importable when running as a script
_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from temper_ai.tools.base import BaseTool, _pydantic_to_llm_schema
from temper_ai.tools.registry import ToolRegistry

GENERATED_HEADER = (
    "<!-- Auto-generated by scripts/generate_tool_docs.py — do not edit manually -->\n"
)

DEFAULT_OUTPUT_DIR = "docs/generated/tools"


# ---------------------------------------------------------------------------
# Schema -> Markdown helpers
# ---------------------------------------------------------------------------


def _yaml_value(value: Any) -> str:
    """Convert a Python default value to its YAML representation."""
    if isinstance(value, bool):
        return "true" if value else "false"
    if value is None:
        return "null"
    return str(value)


def _type_str(prop: dict[str, Any]) -> str:
    """Convert a JSON-schema property to a human-readable type string."""
    t = prop.get("type", "any")
    if t == "array":
        items = prop.get("items", {})
        inner = items.get("type", "any")
        return f"array[{inner}]"
    return str(t)


def _schema_properties_to_rows(
    schema: dict[str, Any],
    include_required: bool = False,
) -> list[dict[str, str]]:
    """Convert JSON-schema properties to a list of row dicts for table rendering."""
    properties = schema.get("properties", {})
    required_set = set(schema.get("required", []))
    rows: list[dict[str, str]] = []
    for name, prop in properties.items():
        row: dict[str, str] = {
            "name": name,
            "type": _type_str(prop),
            "default": _yaml_value(prop["default"]) if "default" in prop else "-",
            "description": prop.get("description", ""),
        }
        if include_required:
            row["required"] = "yes" if name in required_set else "no"
        rows.append(row)
    return rows


def _example_config_entry(config_props: dict[str, Any]) -> tuple[str, str]:
    """Return (key, value) for the YAML config example, preferring props with defaults."""
    type_placeholders = {
        "string": '"/your/path"',
        "array": '["cmd1", "cmd2"]',
        "boolean": "false",
        "integer": "30",
        "number": "1.0",
    }
    # Prefer a property that has a concrete default
    for key, prop in config_props.items():
        if "default" in prop:
            return key, _yaml_value(prop["default"])
    # Fall back to first property with a type-appropriate placeholder
    first_key = next(iter(config_props))
    first_prop = config_props[first_key]
    return first_key, type_placeholders.get(first_prop.get("type", "string"), '"value"')


def _yes_no(val: bool | None) -> str:
    if val is None:
        return "auto"
    return "yes" if val else "no"


# ---------------------------------------------------------------------------
# Per-tool markdown rendering
# ---------------------------------------------------------------------------


def render_tool_markdown(tool: BaseTool) -> str:
    """Render a single tool's documentation as markdown."""
    meta = tool.get_metadata()
    params_schema = tool.get_parameters_schema()
    config_schema = (
        _pydantic_to_llm_schema(tool.config_model)
        if tool.config_model
        else {"type": "object", "properties": {}}
    )
    result_schema = tool.get_result_schema()

    lines: list[str] = [GENERATED_HEADER]
    lines.append(f"# {meta.name}\n")
    lines.append(f"> {meta.description}\n")

    # Metadata table
    lines.append("| Property | Value |")
    lines.append("|----------|-------|")
    lines.append(f"| Version | {meta.version} |")
    lines.append(f"| Category | {meta.category or '-'} |")
    lines.append(f"| Requires network | {_yes_no(meta.requires_network)} |")
    lines.append(f"| Requires credentials | {_yes_no(meta.requires_credentials)} |")
    lines.append(f"| Modifies state | {_yes_no(meta.modifies_state)} |")
    lines.append(f"| Cacheable | {_yes_no(meta.cacheable)} |")
    lines.append("")

    # Parameters
    lines.append("## Parameters\n")
    lines.append("These are sent by the LLM at runtime when it calls the tool.\n")
    param_rows = _schema_properties_to_rows(params_schema, include_required=True)
    if param_rows:
        lines.append("| Name | Type | Required | Default | Description |")
        lines.append("|------|------|----------|---------|-------------|")
        for row in param_rows:
            lines.append(
                f"| {row['name']} | {row['type']} | {row['required']} "
                f"| {row['default']} | {row['description']} |"
            )
    else:
        lines.append("*No parameters.*")
    lines.append("")

    # YAML Config
    config_props = config_schema.get("properties", {})
    lines.append("## YAML Config\n")
    lines.append("Optional overrides passed via the agent YAML config block.\n")
    if config_props:
        config_rows = _schema_properties_to_rows(config_schema)
        lines.append("| Name | Type | Default | Description |")
        lines.append("|------|------|---------|-------------|")
        for row in config_rows:
            lines.append(
                f"| {row['name']} | {row['type']} | {row['default']} | {row['description']} |"
            )
    else:
        lines.append("*No config options.*")
    lines.append("")

    # Usage examples
    tool_name = meta.name
    lines.append("## Usage\n")
    lines.append("### Simple (no config)\n")
    lines.append("```yaml")
    lines.append("agent:")
    lines.append("  tools:")
    lines.append(f'    - "{tool_name}"')
    lines.append("```\n")

    if config_props:
        example_key, example_val = _example_config_entry(config_props)
        lines.append("### With config overrides\n")
        lines.append("```yaml")
        lines.append("agent:")
        lines.append("  tools:")
        lines.append(f'    - name: "{tool_name}"')
        lines.append("      config:")
        lines.append(f"        {example_key}: {example_val}")
        lines.append("```\n")

    # Result schema
    lines.append("## Result Schema\n")
    if result_schema:
        result_rows = _schema_properties_to_rows(result_schema, include_required=True)
        if result_rows:
            lines.append("| Name | Type | Required | Default | Description |")
            lines.append("|------|------|----------|---------|-------------|")
            for row in result_rows:
                lines.append(
                    f"| {row['name']} | {row['type']} | {row['required']} "
                    f"| {row['default']} | {row['description']} |"
                )
        else:
            lines.append("Returns unstructured text.")
    else:
        lines.append("Returns unstructured text.")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Index page
# ---------------------------------------------------------------------------


def render_index_markdown(tools: dict[str, BaseTool]) -> str:
    """Render the index page listing all tools."""
    lines: list[str] = [GENERATED_HEADER]
    lines.append("# Tool Reference\n")
    lines.append("Auto-generated from tool class metadata. Do not edit manually.\n")
    lines.append("| Tool | Category | Description | Network | Credentials |")
    lines.append("|------|----------|-------------|---------|-------------|")

    for name in sorted(tools.keys()):
        tool = tools[name]
        meta = tool.get_metadata()
        safe_name = name.lower().replace(" ", "_")
        lines.append(
            f"| [{meta.name}](./{safe_name}.md) "
            f"| {meta.category or '-'} "
            f"| {meta.description[:80]}{'...' if len(meta.description) > 80 else ''} "
            f"| {_yes_no(meta.requires_network)} "
            f"| {_yes_no(meta.requires_credentials)} |"
        )

    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# JSON output
# ---------------------------------------------------------------------------


def build_json_dump(tools: dict[str, BaseTool]) -> dict[str, Any]:
    """Build the full JSON dump of all tool schemas."""
    tool_data: dict[str, Any] = {}
    for name, tool in sorted(tools.items()):
        meta = tool.get_metadata()
        tool_data[name] = {
            "metadata": {
                "name": meta.name,
                "description": meta.description,
                "version": meta.version,
                "category": meta.category,
                "requires_network": meta.requires_network,
                "requires_credentials": meta.requires_credentials,
                "modifies_state": meta.modifies_state,
                "cacheable": meta.cacheable,
            },
            "parameters_schema": tool.get_parameters_schema(),
            "config_schema": (
                _pydantic_to_llm_schema(tool.config_model)
                if tool.config_model
                else {"type": "object", "properties": {}}
            ),
            "result_schema": tool.get_result_schema(),
        }
    return {
        "generated_at": datetime.now(UTC).isoformat(),
        "tools": tool_data,
    }


# ---------------------------------------------------------------------------
# Main logic
# ---------------------------------------------------------------------------


def discover_tools() -> dict[str, BaseTool]:
    """Discover all tools from the static TOOL_CLASSES registry."""
    from temper_ai.tools import TOOL_CLASSES

    registry = ToolRegistry()
    for name in TOOL_CLASSES:
        registry.get(name)  # Lazy-instantiates and registers
    return registry.get_all_tools()


def generate_markdown(output_dir: Path, tools: dict[str, BaseTool]) -> list[Path]:
    """Generate markdown files for all tools. Returns list of written paths."""
    output_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    # Index page
    index_path = output_dir / "index.md"
    index_path.write_text(render_index_markdown(tools), encoding="utf-8")
    written.append(index_path)

    # Per-tool pages
    for name, tool in sorted(tools.items()):
        safe_name = name.lower().replace(" ", "_")
        tool_path = output_dir / f"{safe_name}.md"
        tool_path.write_text(render_tool_markdown(tool), encoding="utf-8")
        written.append(tool_path)

    return written


def generate_json(output_dir: Path, tools: dict[str, BaseTool]) -> Path:
    """Generate JSON dump of all tool schemas. Returns path to written file."""
    output_dir.mkdir(parents=True, exist_ok=True)
    json_path = output_dir / "tools.json"
    data = build_json_dump(tools)
    json_path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    return json_path


def check_stale(output_dir: Path, tools: dict[str, BaseTool]) -> bool:
    """Check if generated docs are up to date. Returns True if fresh, False if stale."""
    if not output_dir.exists():
        print(f"STALE: output directory {output_dir} does not exist", file=sys.stderr)
        return False

    # Check index
    index_path = output_dir / "index.md"
    if not index_path.exists():
        print(f"STALE: {index_path} does not exist", file=sys.stderr)
        return False
    expected_index = render_index_markdown(tools)
    if index_path.read_text(encoding="utf-8") != expected_index:
        print(f"STALE: {index_path} content differs", file=sys.stderr)
        return False

    # Check per-tool files
    for name, tool in sorted(tools.items()):
        safe_name = name.lower().replace(" ", "_")
        tool_path = output_dir / f"{safe_name}.md"
        if not tool_path.exists():
            print(f"STALE: {tool_path} does not exist", file=sys.stderr)
            return False
        expected = render_tool_markdown(tool)
        if tool_path.read_text(encoding="utf-8") != expected:
            print(f"STALE: {tool_path} content differs", file=sys.stderr)
            return False

    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate tool reference documentation from tool class metadata."
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT_DIR,
        help=f"Output directory (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--format",
        choices=["markdown", "json"],
        default="markdown",
        help="Output format (default: markdown)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Validate existing docs are up to date (exit 1 if stale)",
    )
    args = parser.parse_args()

    output_dir = Path(args.output)
    tools = discover_tools()

    if not tools:
        print("ERROR: No tools discovered", file=sys.stderr)
        return 1

    if args.check:
        if check_stale(output_dir, tools):
            print(f"OK: Tool docs are up to date ({len(tools)} tools)")
            return 0
        else:
            print(
                f"FAIL: Tool docs are stale. Run: python scripts/generate_tool_docs.py --output {output_dir}",
                file=sys.stderr,
            )
            return 1

    if args.format == "json":
        json_path = generate_json(output_dir, tools)
        print(f"Generated JSON for {len(tools)} tools -> {json_path}")
    else:
        written = generate_markdown(output_dir, tools)
        print(f"Generated docs for {len(tools)} tools -> {output_dir}/")
        for p in written:
            print(f"  {p}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
