"""
Problem detection data models for M5 Phase 3.

Defines the data structures for representing performance problems detected
through comparison of current vs baseline agent performance.
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Optional, Dict, Any
from enum import Enum


class ProblemType(Enum):
    """
    Types of performance problems M5 can detect.

    Naming convention: {metric}_{state}
    - metric: quality, cost, speed, error_rate
    - state: low, high

    Each problem type maps to specific improvement strategies:
    - QUALITY_LOW: Prompt tuning, parameter adjustment, model selection
    - COST_HIGH: Cost reduction, caching, cheaper models
    - SPEED_LOW: Speed optimization, model selection, token reduction
    - ERROR_RATE_HIGH: Error rate reduction, retry tuning, model selection
    """
    QUALITY_LOW = "quality_low"
    COST_HIGH = "cost_high"
    SPEED_LOW = "speed_low"
    ERROR_RATE_HIGH = "error_rate_high"


class ProblemSeverity(Enum):
    """
    Problem severity levels for prioritization.

    Determines urgency of improvement actions:
    - CRITICAL: Immediate action required (>50% degradation)
    - HIGH: Action needed soon (30-50% degradation)
    - MEDIUM: Optimization opportunity (15-30% degradation)
    - LOW: Minor issue (5-15% degradation)
    """
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


@dataclass
class PerformanceProblem:
    """
    Represents a detected performance problem.

    Generated by ProblemDetector when comparing current vs baseline performance.
    Used by ImprovementDetector to select appropriate strategies.

    Attributes:
        problem_type: Type of problem detected
        severity: Severity level (CRITICAL, HIGH, MEDIUM, LOW)
        agent_name: Name of affected agent
        metric_name: Specific metric with problem (e.g., "extraction_quality")
        baseline_value: Historical baseline value
        current_value: Current measured value
        degradation_pct: Percentage degradation (current - baseline) / baseline
        threshold_used: Threshold that triggered detection
        detected_at: When problem was detected
        evidence: Supporting data (additional metrics, context)

    Example:
        >>> problem = PerformanceProblem(
        ...     problem_type=ProblemType.QUALITY_LOW,
        ...     severity=ProblemSeverity.MEDIUM,
        ...     agent_name="code_review_agent",
        ...     metric_name="extraction_quality",
        ...     baseline_value=0.85,
        ...     current_value=0.72,
        ...     degradation_pct=-0.153,  # -15.3%
        ...     threshold_used=0.10  # 10% threshold
        ... )
        >>> print(problem.get_summary())
        "MEDIUM quality_low: extraction_quality degraded 15.3% (0.85 → 0.72)"
    """

    # Core identification
    problem_type: ProblemType
    severity: ProblemSeverity
    agent_name: str

    # Metric details
    metric_name: str
    baseline_value: float
    current_value: float
    degradation_pct: float  # Negative for degradation, positive for improvement

    # Detection metadata
    threshold_used: float
    detected_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    # Supporting evidence
    evidence: Dict[str, Any] = field(default_factory=dict)

    def get_summary(self) -> str:
        """Human-readable problem summary."""
        direction = "degraded" if self.degradation_pct < 0 else "improved"
        return (
            f"{self.severity.value.upper()} {self.problem_type.value}: "
            f"{self.metric_name} {direction} {abs(self.degradation_pct)*100:.1f}% "
            f"({self.baseline_value:.3f} → {self.current_value:.3f})"
        )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for storage/serialization."""
        return {
            "problem_type": self.problem_type.value,
            "severity": self.severity.value,
            "agent_name": self.agent_name,
            "metric_name": self.metric_name,
            "baseline_value": self.baseline_value,
            "current_value": self.current_value,
            "degradation_pct": self.degradation_pct,
            "threshold_used": self.threshold_used,
            "detected_at": self.detected_at.isoformat(),
            "evidence": self.evidence,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "PerformanceProblem":
        """Load from dictionary."""
        return cls(
            problem_type=ProblemType(data["problem_type"]),
            severity=ProblemSeverity(data["severity"]),
            agent_name=data["agent_name"],
            metric_name=data["metric_name"],
            baseline_value=data["baseline_value"],
            current_value=data["current_value"],
            degradation_pct=data["degradation_pct"],
            threshold_used=data["threshold_used"],
            detected_at=datetime.fromisoformat(data["detected_at"]),
            evidence=data.get("evidence", {}),
        )
