"""
Data models for M5 Self-Improvement system.

Contains models for agent configuration, performance profiles, improvement proposals,
experiments, and deployment tracking.
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional

from src.constants.durations import DEFAULT_CACHE_TTL_SECONDS, DEFAULT_TIMEOUT_SECONDS
from src.constants.probabilities import PROB_HIGH, PROB_VERY_HIGH_PLUS
from src.constants.retries import (
    DEFAULT_BACKOFF_MULTIPLIER,
    DEFAULT_MAX_RETRIES,
    MIN_BACKOFF_SECONDS,
)
from src.database.datetime_utils import utcnow
from src.self_improvement.constants import (
    FIELD_AGENT_NAME,
    FIELD_COMPLETED_AT,
    FIELD_CREATED_AT,
    FIELD_EXPERIMENT_ID,
    FIELD_EXTRA_METADATA,
    FIELD_METRICS,
    FIELD_RECORDED_AT,
    FIELD_ROLLBACK_AT,
    FIELD_STATUS,
    FIELD_TOTAL_EXECUTIONS,
    FIELD_WINDOW_END,
    FIELD_WINDOW_START,
)

# Configuration constants
ZERO_EXAMPLES = 0


@dataclass
class AgentPerformanceProfile:
    """
    Agent performance profile data model.

    Contains aggregated metrics for an agent over a time window. Generated by
    PerformanceAnalyzer through SQL queries against observability database.

    Metrics dictionary format:
    {
        "metric_name": {
            "mean": float,
            "std": float,      # standard deviation
            "p95": float,      # 95th percentile
            "p99": float,      # 99th percentile (optional)
        }
    }

    Example:
    {
        "success_rate": {"mean": 0.92, "std": 0.05},
        "cost_usd": {"mean": 0.80, "std": 0.12},
        "duration_seconds": {"mean": 42.5, "p95": 55.0, "std": 8.5},
        "quality_score": {"mean": 0.75, "std": 0.08},
    }

    Used by:
    - ImprovementDetector to compare current vs baseline performance
    - Dashboard/UI for displaying agent performance trends
    - Alerting system for detecting performance degradation
    """

    # Identity (required fields first)
    agent_name: str

    # Time window (required)
    window_start: datetime
    window_end: datetime

    # Execution count (required)
    total_executions: int

    # Optional fields with defaults
    profile_id: Optional[str] = None  # Auto-generated on storage

    # Aggregated metrics
    # Key: metric_name, Value: {"mean": X, "std": Y, "p95": Z, ...}
    metrics: Dict[str, Dict[str, float]] = field(default_factory=dict)

    # Metadata
    created_at: datetime = field(default_factory=utcnow)
    extra_metadata: Dict[str, Any] = field(default_factory=dict)

    def get_metric(self, metric_name: str, stat: str = "mean") -> Optional[float]:
        """Get a specific metric statistic."""
        metric_data = self.metrics.get(metric_name)
        if metric_data is None:
            return None
        return metric_data.get(stat)

    def has_metric(self, metric_name: str) -> bool:
        """Check if profile contains a metric."""
        return metric_name in self.metrics

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return {
            "profile_id": self.profile_id,
            FIELD_AGENT_NAME: self.agent_name,
            FIELD_WINDOW_START: self.window_start.isoformat(),
            FIELD_WINDOW_END: self.window_end.isoformat(),
            FIELD_TOTAL_EXECUTIONS: self.total_executions,
            FIELD_METRICS: self.metrics,
            FIELD_CREATED_AT: self.created_at.isoformat(),
            FIELD_EXTRA_METADATA: self.extra_metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "AgentPerformanceProfile":
        """Load from dictionary (e.g., from database)."""
        return cls(
            profile_id=data.get("profile_id"),
            agent_name=data[FIELD_AGENT_NAME],
            window_start=datetime.fromisoformat(data[FIELD_WINDOW_START]),
            window_end=datetime.fromisoformat(data[FIELD_WINDOW_END]),
            total_executions=data[FIELD_TOTAL_EXECUTIONS],
            metrics=data.get(FIELD_METRICS, {}),
            created_at=datetime.fromisoformat(data.get(FIELD_CREATED_AT, utcnow().isoformat())),
            extra_metadata=data.get(FIELD_EXTRA_METADATA, {}),
        )


@dataclass
class SIOptimizationConfig:
    """
    Agent configuration data model.

    Represents the configurable parameters for an agent that M5 can optimize.
    This includes inference settings, prompt configuration, and tool settings.

    Used by:
    - ImprovementStrategy to generate config variants
    - ExperimentOrchestrator to test different configurations
    - ConfigDeployer to deploy winning configurations
    """

    # Identity
    agent_name: str
    agent_version: str = "1.0.0"

    # Inference configuration
    inference: Dict[str, Any] = field(default_factory=lambda: {
        "provider": "ollama",
        "model": "llama3.1:8b",
        "temperature": PROB_HIGH,
        "max_tokens": 2048,
        "top_p": PROB_VERY_HIGH_PLUS,
        "base_url": None,
    })

    # Prompt configuration
    prompt: Dict[str, Any] = field(default_factory=lambda: {
        "template": None,
        "include_examples": False,
        "num_examples": ZERO_EXAMPLES,
        "include_reasoning_guide": False,
        "include_citations": False,
        "require_source_verification": False,
        "sections": [],
    })

    # Tool configuration
    tools: Dict[str, Any] = field(default_factory=lambda: {
        "enabled_tools": [],
        "tool_timeout_seconds": DEFAULT_TIMEOUT_SECONDS,
        "max_retries": DEFAULT_MAX_RETRIES,
        "safety_checks": True,
    })

    # Caching configuration
    caching: Dict[str, Any] = field(default_factory=lambda: {
        "enabled": False,
        "cache_type": "memory",
        "ttl_seconds": DEFAULT_CACHE_TTL_SECONDS,
    })

    # Retry configuration
    retry: Dict[str, Any] = field(default_factory=lambda: {
        "max_retries": DEFAULT_MAX_RETRIES,
        "backoff_multiplier": DEFAULT_BACKOFF_MULTIPLIER,
        "initial_delay_seconds": MIN_BACKOFF_SECONDS,
    })

    # Metadata
    extra_metadata: Dict[str, Any] = field(default_factory=dict)

    def copy(self) -> "SIOptimizationConfig":
        """Create a deep copy of this config for generating variants."""
        import copy
        return SIOptimizationConfig(
            agent_name=self.agent_name,
            agent_version=self.agent_version,
            inference=copy.deepcopy(self.inference),
            prompt=copy.deepcopy(self.prompt),
            tools=copy.deepcopy(self.tools),
            caching=copy.deepcopy(self.caching),
            retry=copy.deepcopy(self.retry),
            extra_metadata=copy.deepcopy(self.extra_metadata),
        )

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return {
            FIELD_AGENT_NAME: self.agent_name,
            "agent_version": self.agent_version,
            "inference": self.inference,
            "prompt": self.prompt,
            "tools": self.tools,
            "caching": self.caching,
            "retry": self.retry,
            FIELD_EXTRA_METADATA: self.extra_metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SIOptimizationConfig":
        """Load from dictionary (e.g., from database)."""
        return cls(
            agent_name=data[FIELD_AGENT_NAME],
            agent_version=data.get("agent_version", "1.0.0"),
            inference=data.get("inference", {}),
            prompt=data.get("prompt", {}),
            tools=data.get("tools", {}),
            caching=data.get("caching", {}),
            retry=data.get("retry", {}),
            extra_metadata=data.get(FIELD_EXTRA_METADATA, {}),
        )


@dataclass
class SelfImprovementExperiment:
    """
    Experiment data model for A/B/C/D testing configurations.

    Represents a running or completed experiment that tests multiple configuration
    variants against a control to find optimal agent settings.

    Used by:
    - ExperimentOrchestrator to create and manage experiments
    - StatisticalAnalyzer to analyze results and pick winners
    - ExperimentAssignment to route executions to variants
    """

    # Identity
    id: str
    agent_name: str

    # Status
    status: str  # 'running', 'completed', 'failed'

    # Configuration being tested
    control_config: SIOptimizationConfig
    variant_configs: List[SIOptimizationConfig]

    # Metadata
    proposal_id: Optional[str] = None
    created_at: datetime = field(default_factory=utcnow)
    completed_at: Optional[datetime] = None
    extra_metadata: Dict[str, Any] = field(default_factory=dict)

    def get_all_configs(self) -> Dict[str, SIOptimizationConfig]:
        """
        Get all configurations (control + variants) as a dictionary.

        Returns:
            Dict mapping variant_id to config:
            {
                "control": <SIOptimizationConfig>,
                "variant_0": <SIOptimizationConfig>,
                "variant_1": <SIOptimizationConfig>,
                ...
            }
        """
        configs = {"control": self.control_config}
        for i, variant in enumerate(self.variant_configs):
            configs[f"variant_{i}"] = variant
        return configs

    def get_variant_count(self) -> int:
        """Get total number of variants (including control)."""
        return 1 + len(self.variant_configs)

    def is_running(self) -> bool:
        """Check if experiment is still running."""
        return self.status == "running"

    def is_completed(self) -> bool:
        """Check if experiment has completed."""
        return self.status == "completed"

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return {
            "id": self.id,
            FIELD_AGENT_NAME: self.agent_name,
            FIELD_STATUS: self.status,
            "control_config": self.control_config.to_dict(),
            "variant_configs": [v.to_dict() for v in self.variant_configs],
            "proposal_id": self.proposal_id,
            FIELD_CREATED_AT: self.created_at.isoformat(),
            FIELD_COMPLETED_AT: self.completed_at.isoformat() if self.completed_at else None,
            FIELD_EXTRA_METADATA: self.extra_metadata,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "SelfImprovementExperiment":
        """Load from dictionary (e.g., from database)."""
        return cls(
            id=data["id"],
            agent_name=data[FIELD_AGENT_NAME],
            status=data[FIELD_STATUS],
            control_config=SIOptimizationConfig.from_dict(data["control_config"]),
            variant_configs=[SIOptimizationConfig.from_dict(v) for v in data.get("variant_configs", [])],
            proposal_id=data.get("proposal_id"),
            created_at=datetime.fromisoformat(data[FIELD_CREATED_AT]),
            completed_at=datetime.fromisoformat(data[FIELD_COMPLETED_AT]) if data.get(FIELD_COMPLETED_AT) else None,
            extra_metadata=data.get(FIELD_EXTRA_METADATA, {}),
        )


@dataclass
class ExecutionResult:
    """
    Single execution result within an experiment.

    Records the outcome of one agent execution during an experiment,
    tracking which variant was used and the performance metrics achieved.

    Used by:
    - StatisticalAnalyzer to compare variant performance
    - ExperimentOrchestrator to track completion progress
    """

    # Identity
    id: str
    experiment_id: str
    variant_id: str  # 'control', 'variant_0', 'variant_1', etc.
    execution_id: str

    # Metrics
    quality_score: Optional[float] = None
    speed_seconds: Optional[float] = None
    cost_usd: Optional[float] = None
    success: Optional[bool] = None

    # Metadata
    recorded_at: datetime = field(default_factory=utcnow)
    extra_metrics: Dict[str, float] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return {
            "id": self.id,
            FIELD_EXPERIMENT_ID: self.experiment_id,
            "variant_id": self.variant_id,
            "execution_id": self.execution_id,
            "quality_score": self.quality_score,
            "speed_seconds": self.speed_seconds,
            "cost_usd": self.cost_usd,
            "success": self.success,
            FIELD_RECORDED_AT: self.recorded_at.isoformat(),
            "extra_metrics": self.extra_metrics,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ExecutionResult":
        """Load from dictionary (e.g., from database)."""
        return cls(
            id=data["id"],
            experiment_id=data[FIELD_EXPERIMENT_ID],
            variant_id=data["variant_id"],
            execution_id=data["execution_id"],
            quality_score=data.get("quality_score"),
            speed_seconds=data.get("speed_seconds"),
            cost_usd=data.get("cost_usd"),
            success=data.get("success"),
            recorded_at=datetime.fromisoformat(data[FIELD_RECORDED_AT]),
            extra_metrics=data.get("extra_metrics", {}),
        )


@dataclass
class ConfigDeployment:
    """
    Configuration deployment record for tracking rollback history.

    Records each configuration change made to an agent, storing both the
    previous and new configurations to enable rollback if needed.

    Used by:
    - ConfigDeployer to track deployment history
    - Rollback mechanism to revert to previous configurations
    """

    # Identity
    id: str
    agent_name: str

    # Configurations
    previous_config: SIOptimizationConfig
    new_config: SIOptimizationConfig

    # Deployment metadata
    experiment_id: Optional[str] = None
    deployed_at: datetime = field(default_factory=utcnow)
    deployed_by: str = "m5_system"

    # Rollback tracking
    rollback_at: Optional[datetime] = None
    rollback_reason: Optional[str] = None

    def is_rolled_back(self) -> bool:
        """Check if this deployment has been rolled back."""
        return self.rollback_at is not None

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return {
            "id": self.id,
            FIELD_AGENT_NAME: self.agent_name,
            "previous_config": self.previous_config.to_dict(),
            "new_config": self.new_config.to_dict(),
            FIELD_EXPERIMENT_ID: self.experiment_id,
            "deployed_at": self.deployed_at.isoformat(),
            "deployed_by": self.deployed_by,
            FIELD_ROLLBACK_AT: self.rollback_at.isoformat() if self.rollback_at else None,
            "rollback_reason": self.rollback_reason,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "ConfigDeployment":
        """Load from dictionary (e.g., from database)."""
        return cls(
            id=data["id"],
            agent_name=data[FIELD_AGENT_NAME],
            previous_config=SIOptimizationConfig.from_dict(data["previous_config"]),
            new_config=SIOptimizationConfig.from_dict(data["new_config"]),
            experiment_id=data.get(FIELD_EXPERIMENT_ID),
            deployed_at=datetime.fromisoformat(data["deployed_at"]),
            deployed_by=data.get("deployed_by", "m5_system"),
            rollback_at=datetime.fromisoformat(data[FIELD_ROLLBACK_AT]) if data.get(FIELD_ROLLBACK_AT) else None,
            rollback_reason=data.get("rollback_reason"),
        )


@dataclass
class StrategyOutcome:
    """
    Tracks actual outcomes from strategy applications for learning.

    Records the real-world results when a strategy is applied and tested
    through experimentation. Used to refine estimate_impact() predictions
    over time through Bayesian updating or moving averages.

    Attributes:
        id: Unique outcome identifier
        strategy_name: Name of strategy that was applied
        problem_type: Type of problem addressed (quality_low, cost_high, etc.)
        agent_name: Name of agent this was applied to
        experiment_id: ID of experiment that tested this strategy
        was_winner: Whether this strategy's variant won the experiment
        actual_quality_improvement: Actual quality improvement (0.0-1.0, negative if degraded)
        actual_speed_improvement: Actual speed improvement (0.0-1.0, negative if slower)
        actual_cost_improvement: Actual cost improvement (0.0-1.0, negative if more expensive)
        composite_score: Combined improvement score
        confidence: Statistical confidence of the result (0.0-1.0)
        sample_size: Number of executions used in experiment
        recorded_at: When this outcome was recorded
        context: Additional context (current config, patterns, etc.)
    """

    # Identity
    id: str
    strategy_name: str
    problem_type: str
    agent_name: str

    # Experiment linkage
    experiment_id: str
    was_winner: bool

    # Actual improvement metrics
    actual_quality_improvement: float  # Fraction: 0.3 = 30% improvement
    actual_speed_improvement: float
    actual_cost_improvement: float
    composite_score: float

    # Statistical confidence
    confidence: float
    sample_size: int

    # Metadata
    recorded_at: datetime = field(default_factory=utcnow)
    context: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary for database storage."""
        return {
            "id": self.id,
            "strategy_name": self.strategy_name,
            "problem_type": self.problem_type,
            FIELD_AGENT_NAME: self.agent_name,
            FIELD_EXPERIMENT_ID: self.experiment_id,
            "was_winner": self.was_winner,
            "actual_quality_improvement": self.actual_quality_improvement,
            "actual_speed_improvement": self.actual_speed_improvement,
            "actual_cost_improvement": self.actual_cost_improvement,
            "composite_score": self.composite_score,
            "confidence": self.confidence,
            "sample_size": self.sample_size,
            FIELD_RECORDED_AT: self.recorded_at.isoformat(),
            "context": self.context,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "StrategyOutcome":
        """Load from dictionary (e.g., from database)."""
        return cls(
            id=data["id"],
            strategy_name=data["strategy_name"],
            problem_type=data["problem_type"],
            agent_name=data[FIELD_AGENT_NAME],
            experiment_id=data[FIELD_EXPERIMENT_ID],
            was_winner=data["was_winner"],
            actual_quality_improvement=data["actual_quality_improvement"],
            actual_speed_improvement=data["actual_speed_improvement"],
            actual_cost_improvement=data["actual_cost_improvement"],
            composite_score=data["composite_score"],
            confidence=data["confidence"],
            sample_size=data["sample_size"],
            recorded_at=datetime.fromisoformat(data[FIELD_RECORDED_AT]),
            context=data.get("context", {}),
        )
